# Generated by Django 4.2.1 on 2023-05-26 08:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import pfe_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe_app', '0014_user_online'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='no_future_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='color',
        ),
        migrations.RemoveField(
            model_name='user',
            name='online',
        ),
        migrations.AlterField(
            model_name='cluster',
            name='cluster_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='cluster_id',
            field=models.ForeignKey(default=pfe_app.models.get_default_cluster_id, on_delete=django.db.models.deletion.CASCADE, to='pfe_app.cluster'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('date_of_birth__lte', datetime.date(2023, 5, 26))), name='no_future_date_of_birth'),
        ),
    ]
