# Generated by Django 4.2.1 on 2023-05-30 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe_app', '0015_remove_user_no_future_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='no_future_date_of_birth',
        ),
        migrations.AddField(
            model_name='cluster',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='if_transmit',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('date_of_birth__lte', datetime.date(2023, 5, 30))), name='no_future_date_of_birth'),
        ),
    ]
